### ISSUE TITLE
Open C# colorizing issues

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#101]
FYI I created the following bugs against https://github.com/atom/language-csharp from issues reported against the c# snytax highlighting in VS Code.
I will close the corresponding bugs in the VSCode repository that we kept open to track any progress.

https://github.com/atom/language-csharp/issues/48
https://github.com/atom/language-csharp/issues/46
https://github.com/atom/language-csharp/issues/43
https://github.com/atom/language-csharp/issues/44
https://github.com/atom/language-csharp/issues/45

**Comment by ivanz** [comment]
@DustinCampbell FYI All but one of those are fixed and I have created a separate issue for it here #687 - so you can close this one. I have an idea how to fix the remaining one and will have a look when I get a chance.

**Comment by DustinCampbell** [comment]
@ivanz, do you think it'd make sense to port your fixes over to the (https://github.com/atom/language-csharp) repo?

**Comment by DustinCampbell** [comment]
cc @david-driscoll as well. I'm not sure if the OmniSharp extension for Atom uses the same grammar or not.

**Comment by david-driscoll** [comment]
Yeah, we use the built in csharp grammar from atom.  The semantic highlighting is additive.

**Comment by DustinCampbell** [comment]
Cool. So, porting these fixes to atom would be good for you too.

**Comment by david-driscoll** [comment]
If you port them (which would be amazing!) feel free to cc me on the pull request.  :+1:

**Comment by DustinCampbell** [comment]
All of these are fixed for the next release.

**Comment by joshpritchard-fcx** [comment]
This release did not fix https://github.com/Microsoft/vscode/issues/848 so it should be re-opened. This is very annoying for me.

**Comment by DustinCampbell** [comment]
@joshpritchard-fcx : Here's what the https://github.com/Microsoft/vscode/issues/848 repro looks like it the latest release of VS Code:

![image](https://user-images.githubusercontent.com/116161/35292276-da236fe8-0024-11e8-88a0-bfd0b6aa66fe.png)

This appears to be correct to me. If you disagree, please feel free to file a new issue at https://github.com/dotnet/csharp-tmLanguage/issues.

**Comment by joshpritchard-fcx** [comment]
Thanks. Sorry for commenting here I guess what I am seeing is a separate issue.
