### ISSUE TITLE
Using omnisharp latest setting causes omnisharp to fail downloading with 404

### ISSUE THREAD

**Issue by divinebovine** [OmniSharp/omnisharp-vscode#2473]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.1.9 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
VS Code version: 1.26.1
C# Extension version: 1.15.2

## Steps to reproduce
Set `"omnisharp.path": "latest"` in user settings
Open an existing project c# project
Watch C# output window

## Expected  behavior
vscode downloads the latest omnisharp

## Actual behavior
```
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 3.5.0-beta.1858...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 3.5.0-beta.1858' failed (error code '404')
Failed at stage: downloadAndInstallPackages
404
```

**Comment by akshita31** [comment]
@divinebovine Thank you for filing the issue. We are looking into it.

**Comment by rchande** [comment]
@divinebovine Thanks--the 404 should be resolved.

**Comment by akshita31** [comment]
Yeah this is fixed now. @rchande Shall we close this one ?

**Comment by divinebovine** [comment]
Hey guys, thanks for looking into this, but I'm still experiencing the 404.

**Comment by rchande** [comment]
@divinebovine Should be fixed (again) (and not regress). Try again?

**Comment by divinebovine** [comment]
@rchande thanks, it appears to be fixed.

**Comment by Logerfo** [comment]
Yeah, this is happening again. A new VSCode version was released yesterday, which might not be a coincidence.

**Comment by akshita31** [comment]
@Logerfo @RunninglVlan It seems to be fixed for me. Can you try again ?

**Comment by Logerfo** [comment]
Yes, it's also fixed for me.

**Comment by Lite5h4dow** [comment]
having the same issue again.

```
Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.11-beta.1' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.11-beta.1/omnisharp-win-x64.zip. Error code '404')
Failed at stage: downloadAndInstallPackages
404
```

**Comment by Lite5h4dow** [comment]
```
Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.11-beta.1' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.11-beta.1/omnisharp-win-x64.zip. Error code '404')
Failed at stage: downloadAndInstallPackages
404
```

Having the same issue again.

**Comment by bitfrickler** [comment]
> ```
> Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.11-beta.1' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.11-beta.1/omnisharp-win-x64.zip. Error code '404')
> Failed at stage: downloadAndInstallPackages
> 404
> ```
> Having the same issue again.

Same here.

**Comment by rchande** [comment]
Hi all, the build step that uploads these ran into an error--I restarted it and this should be resolved now.

**Comment by MeSurajYadav** [comment]
Can you give it a try, coz it worked for me. I had some settings in my settings.json file like proxy settings, omnisharp path etc. But, it failed when I switched to dotnet core 3 and new latest VS Code.
When I emptied out all the settings in settings.json VS code automatically downloaded all the required files and worked. Keep {} only in File->Preferences->Settings.Json (comment all settings) and see if it fixes as its working for me now. [Note, i have proxy settings in cmd(env variables) and .npmrc as internet is necessary]
