### ISSUE TITLE
Conditional breakpoint fails to evaluate a string property 

### ISSUE THREAD

**Issue by dubeg** [OmniSharp/omnisharp-vscode#2683]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

VS Code version: 1.29.0
C# Extension version: 1.17.0

## Steps to reproduce
- Add a conditional breakpoint evaluating a string property of an instance.
- Start a debug session and hit the breakpoint.

## Expected  behavior
The conditional breakpoint works.

## Actual behavior
There's an error in the debug console, and the breakpoint is hit regardless of the condition.

>The condition for a breakpoint failed to execute. The condition was 'item.No == "xxx"'. The error returned was 'Evaluation of method System.String.op_Equality() calls into native method System.Environment.FailFast(). Evaluation of native methods in this context is not supported.'.

## Additional notes
I tried finding a similar issue in this repo, but I couldn't find any. However, I found this [issue](https://developercommunity.visualstudio.com/content/problem/314822/the-condition-for-a-breakpoint-failed-to-execute-e.html) which is filed under Visual Studio 2017 15.8, which I have installed (v15.8.9 to be specific). 

Could it be that my VS 2017 15.8's debugger takes precedence over the debugger of Omnisharp? Is there a way to tell Omnisharp to use the one it's included with?

**Comment by gregg-miskelly** [comment]
The C# debugger backend is mostly shared between VS and VS Code. So you are just running into the same bug in both debuggers.

**Comment by dubeg** [comment]
Here's a minimum repro:
```
using System;
using System.Collections.Generic;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            // var str = "AAAAAAAAA"; // Works
            var str = "AAAAAAAA1"; // Fails
            // Expression: str == "AAAAAAAAA"
            Console.Write(str);
        }
    }
}
```

**Comment by gregg-miskelly** [comment]
Note for anyone reading this, here are the two VS Feedback tickets that also reference the same underlying issue:

* https://developercommunity.visualstudio.com/content/problem/383554/debugger-error-when-comparing-strings-net-core.html
* https://developercommunity.visualstudio.com/content/problem/314822/the-condition-for-a-breakpoint-failed-to-execute-e.html -- not everyone reporting through this ticket is running into this for .NET Core strings, but some certainly are

**Comment by gregg-miskelly** [comment]
This is now fixed in 1.18.

**Comment by ddobric** [comment]
Sorry, still have the same issue: 

> Microsoft Visual Studio Enterprise 2019
> Version 16.4.5

![image](https://user-images.githubusercontent.com/1756871/74284118-66ac8d80-4d23-11ea-9a4d-4342794b0d31.png)

**Comment by JoeRobich** [comment]
Hi @ddobric, You can report Visual Studio issues using "Send Feedback" from the top right corner of Visual Studio. This repository is strictly for the C# extension for VS Code.

![image](https://user-images.githubusercontent.com/611219/74285332-7653b400-4cda-11ea-95d8-e89316a49950.png)
