### ISSUE TITLE
VSCode v1.1.1 with omnisharp v1.0.10 which needs install dotnet cli tools cannot list symbols in file and cannot find symbols in the solution

### ISSUE THREAD

**Issue by lishali12345** [OmniSharp/omnisharp-vscode#331]
I just upgrade the latest stable VSCode v1.1.1, and upgrade the csharp plugin to v1.0.10.

Then I got a hint to install the dotnet, and I follow this instructions [here](https://www.microsoft.com/net/core#macosx).

After that I add the /usr/local/share/dotnet to the Path, restart  the VSCode, the warning of missing CLI Tools is gone. But I can not find symbols in the solution or find symbols in a file any more. And I got nothing error log or anything else that  I can paste here.

**Comment by lishali12345** [comment]
I'm sorry to say that I have fixed this issue. But I'm not very clear to the fix. So I will put it out here.

I'm working on a Unity3D project on Mac OSX EI Capitan, so I use the VSCode plugin in Unity3D and VSCode with some extensions just like: OmniSharp, Debugger for Unity and Unity Tools.

Before I upgrade the VSCode to the latest stable version v1.1.1 and CSharp extension to v1.0.10, I can use "Open C# Project In Code" to open the whole project in VSCode, and everything is ok, I can find symbols in solution and list all the symbols just in the opened source file. 

Now I should run "dotnet new" and "dotnet restore" in the Unity3D project folder, which will generate two files named "project.json" and "project.lock.json". After this, I can open the Unity3D project folder in the VSCode, and I can find symbols in solution and file again.

I had check the content in the "project.json" file, I found there is an config item which import "dnxcore50", maybe it's the fix by this config item, I don't know.

**Comment by Souk21** [comment]
I just upgraded too, and was faced to the same problem. (also using Unity)
I tried your workaround, and it works, but omnisharp doesn't recognize Unity API (UnityEngine, MonoBehaviour,... are considered as errors).

**Comment by mbektimirov** [comment]
Same updates for vs code and c# plugin and intellisense completely stopped. Reinstalling and relaunching the ide doesn't solve the issue.

**Comment by DustinCampbell** [comment]
Hi! Sorry you're running into problems. MSBuild support has been temporarily removed from the extension on OS X and Linux in the latest release. If you're working with Unity on OS X, check the instructions on our https://github.com/OmniSharp/omnisharp-vscode/blob/master/README.md. The steps in the readme help you download and install an older version of the extension (be sure to remove the C# extension first). We're working on finding a better workaround to use with the latest C# extension.

**Comment by TheWanderingTree** [comment]
Was running into this issue as well! It was not clear to me that I needed to uninstall the C# extension in order for the Built-In Omnisharp extension to work. Highly recommend adding that to the readme.

**Comment by DustinCampbell** [comment]
Thanks @TheWanderingTree. Will do so! Once the C# extension is uninstalled, does the old (terribly-named) "Build-In Omnisharp" work for you?

**Comment by TheWanderingTree** [comment]
Yes it does!

**Comment by DustinCampbell** [comment]
Excellent! Thanks for verifying.

**Comment by lishali12345** [comment]
@Souk21 Yes, after that I found the same problem. And I tried to import the local UnityEngine.dll and other assembly in the project.json file located in the root folder of the unity3d project, but I failed again. Let's wait for the next release to fix this. Now I'm using the built-in OmniSharp extension to work.

**Comment by diegogonzalez** [comment]
Hi, where I can find the "Built-in Omnisharp"? It is not enabled on the Visual Studio Code 1.1.1.

**Comment by DustinCampbell** [comment]
Try this @diegogonzalez: https://marketplace.visualstudio.com/items?itemName=ms-vscode.omnisharp

**Comment by diegogonzalez** [comment]
Thanks @DustinCampbell It works!!!

**Comment by DustinCampbell** [comment]
I've updated both the [C# Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) and the [Legacy C# Support Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.omnisharp) (previously called "Build-in Omnisharp") to have better describe the situation and provide clearer instructions.

@lishali12345, @Souk21, @mbektimirov: Does the Legacy C# Support Extension work for you?

Thanks to @TheWanderingTree and @diegogonzalez for confirming that this workaround solves your immediate problem.

**Comment by Asuka786546058** [comment]
My Mac vscode omnisharp has been running for several hours in the past or have been running display

**Comment by Souk21** [comment]
> Does the Legacy C# Support Extension work for you?

Yes it does ! Thanks

**Comment by lishali12345** [comment]
@DustinCampbell Yes it does! Thanks for your work!

**Comment by DustinCampbell** [comment]
That's great to hear. Thanks everyone! Again, I want to reiterate this is a temporary problem. We will be bringing support back to the C# Extension in the near future.
