### ISSUE TITLE
Failing syntax highlighting when using `await foreach`

### ISSUE THREAD

**Issue by koliyo** [OmniSharp/omnisharp-vscode#3666]
## Environment data
C# Extension version:
ms-dotnettools.csharp: version 1.21.14

## Steps to reproduce
The syntax highlighting is broken for `await foreach` usage.

Basically all code after the `await foreach` declaration becomes broken

eg this snippet
```cs
public class Foo {
  public override async Task waitTask(Brick.Grpc.StringMsg task, IServerStreamWriter<Bamse.Grpc.Any_Task_TaskEvent> streamWriter, ServerCallContext context) {
    var stream = Bamse.Session.Default.Hub.waitTask(task);
    await foreach (var e in stream.ResponseStream.ReadAllAsync()) {
      await streamWriter.WriteAsync(e);
    }
  }

  public override async Task<Brick.Grpc.Void> revokeTask(Brick.Grpc.StringMsg task, ServerCallContext context) {
    return await Bamse.Session.Default.Hub.revokeTaskAsync(task);
  }
}
```

Screenshot for reference:
![Screenshot 2020-03-14 at 10 07 15](https://user-images.githubusercontent.com/770348/76678848-a2b16780-65db-11ea-81aa-29ebbf8e4a7a.png)

**Comment by jmarolf** [comment]
this should be moved to dotnet/csharp-tmLanguage

**Comment by JoeRobich** [comment]
This issue will be resolved once the semantic token api is introduced in the release build.

**Comment by doodlefolks** [comment]
Any idea when this will make it into release?

**Comment by eug48** [comment]
@doodlefolks @koliyo this is now fixed - just turn on `editor.semanticHighlighting.enabled`

**Comment by watsonpaul6** [comment]
@eug48 I have editor.semanticHighlighting.enabled set to true but it has not fixed it for me. vscode version 1.55.2, c# extension version 1.23.11

**Comment by JoeRobich** [comment]
`csharp.semanticHighlighting.enabled` also needs to be set to `true`
