### ISSUE TITLE
Rename folder and class file breaks omnisharp lookup

### ISSUE THREAD

**Issue by scyentyfyc** [OmniSharp/omnisharp-vscode#3852]
Issue Type: <b>Bug</b>

Whenever I change a folder name, immediately followed by changing a file name in that folder, OmniSharp begins to fail on lookup of that class (and lights up with "errors" anywhere that class is used).

Similar to this issue, but definitely happening on Windows, not just OSX: https://github.com/OmniSharp/omnisharp-vscode/issues/2040

Extension version: 1.22.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.86GB free)|
|Process Argv|C:\sc\ado-criver\BRAIN\AIM-Regression-Tests|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cartermp** [comment]
@scyentyfyc this should be resolved with the latest release, 1.22.1. Could you install that and report back?

**Comment by scyentyfyc** [comment]
It is partially fixed.  I again renamed the folder, then renamed the file as previously reported, and references to the class in that file are now found \ can do the lookup, but NOW... I'm having using directive lookup problems, and here is now that manifests.

I have other files in the same folder (that was just renamed), containing classes in a namespace different from the file that was just renamed.  The class in the renamed file, uses a class in that other namespace, and the using directive to that other namespace is now not resolving (unless I restart omnisharp).

**Comment by scyentyfyc** [comment]
This is weird.  I also just noticed now, that if I only rename the folder, but don't rename the file in the folder, that the lookups to the class don't work after I rename the folder, but if I then proceed to rename the file, it "fixes" the lookups to the class.  To be clear, this is a re-manifestation of the original problem, just in a slightly different way, i.e. only rename the folder.  The other problem with the namespace, noted above, is a separate problem altogether.  Just in case, here is the Omnisharp server startup output... pretty sure I'm up to the current version.

Starting OmniSharp server at 6/18/2020, 12:10:44 PM
    Target: c:\sc\ado-criver\BRAIN\AIM-Regression-Tests\aim-regression-tests.sln

OmniSharp server started.
    Path: c:\Users\cr212617\.vscode\extensions\ms-dotnettools.csharp-1.22.1\.omnisharp\1.35.3\OmniSharp.exe
    PID: 4320

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)

**Comment by SirIntruder** [comment]
I think the last update handled the "directory deleted" event, but not the "directory added" event. 

So after renaming folder, documents get removed from the project model, but they don't get added under new path (until you give them specific "file changed" event, that is)

**Comment by scyentyfyc** [comment]
Today I got it again when I renamed a folder.  OmniSharp highlighted everything red that depended on the classes inside that renamed folder.  had to restart OmniSharp server

During OmniSharp server start, my file version looked like: .vscode\extensions\ms-dotnettools.csharp-1.22.1\.omnisharp\1.35.3\OmniSharp.exe

**Comment by SirIntruder** [comment]
@savpek Could we fix this by iterating through "added" (new path after rename) directory and triggering OnFileAdded() code path for each `.cs` file? Only other alternative I can think of is to queue project rebuild for projects which include the new folder.

**Comment by savpek** [comment]
I don't know if this is  releated to folder removal directly. **/*.* works with folders when they are added but it doesn't raise event on removed files if folder is removed. 

I think this is releated to how renamed files are handled internally at omnisharp 🤔 Could be something to do with transient/non transient state after rename of file. But this seems relatively easy to reproduce so debugging through is probably easiest option.

**Comment by SirIntruder** [comment]
The issue happens after renaming folders, not renaming specific file. So that should raise "folder removed" event + "folder added" event?

**Comment by mariusmathisen** [comment]
Any progress on this issue ? Since it is not fixed yet - does that mean that it works for most people ?
