### ISSUE TITLE
Named argument without colon

### ISSUE THREAD

**Issue by iSazonov** [OmniSharp/omnisharp-vscode#4103]
Issue Type: <b>Bug</b>

If I type a named argument a recomendation notify shows me full name of the parameter with colon on the end. But after I pess Enter to insert the name only the name is inserted without colon.
Expected behavior - the paramter name is inserted with colon on end.

![image](https://user-images.githubusercontent.com/22290914/95574473-6eedd180-0a46-11eb-8b1d-64bede1a5dc7.png)

![image](https://user-images.githubusercontent.com/22290914/95574506-790fd000-0a46-11eb-8ddb-bc74457f8b18.png)

Extension version: 1.23.2
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.40GB free)|
|Process Argv|--crash-reporter-id a4f7808b-f735-44a7-add9-c658fbcfd849|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by filipw** [comment]
This is already fixed and will ship in the next release of OmniSharp.

**Comment by 333fred** [comment]
@filipw this is not fixed, it's not Roslyn's behavior. https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/Completion/CompletionProviders/NamedParameterCompletionProvider.cs#L286 shows what they do: if `(` is pressed, it includes the `:`, otherwise it does not. We also do not have support for the conditional include on `(`, as vscode does not have the ability to do that, but our behavior here is in line with VS.

**Comment by iSazonov** [comment]
> This is already fixed and will ship in the next release of OmniSharp.

I confirm.
