### ISSUE TITLE
Formatting Razor File errors with "Request textDocument/formatting failed"

### ISSUE THREAD

**Issue by seangwright** [OmniSharp/omnisharp-vscode#5561]
## Issue Description ##
When I try to format a Razor file, the formatting fails and I see an error.

## Steps to Reproduce ##
- Create a `.cshtml` file
- Add some markup (can be simple HTML)
- Format the document (either `alt+shift+f` or format on save)

## Expected Behavior ##
The document is formatted and there are no errors

## Actual Behavior ##
The document does not format and VS Code displays an error

https://user-images.githubusercontent.com/1382768/214971355-d141d099-5863-4ee6-b882-08e327faca74.mp4

### OmniSharp log ###
No errors

### C# log ###
No errors

### Razor Log ###

```
[Error - 6:07:07 PM] [null]
[Error - 6:07:07 PM] Request textDocument/formatting failed.
  Message: Specified argument was out of the range of valid values. (Parameter 'Range start line 3 matches or exceeds SourceText boundary 3.')
  Code: -32000 
[object Object]
```

## Environment information ##

**VSCode version**: 1.74.3
**C# Extension**: 1.25.4

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.308 [C:\Program Files\dotnet\sdk]
  6.0.403 [C:\Program Files\dotnet\sdk]
  6.0.405 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.11.3|
|azure-pipelines|ms-azure-devops|1.208.0|
|carbon-now-sh|ericadamski|1.2.0|
|csharp|ms-dotnettools|1.25.4|
|docomment|k--kato|0.1.32|
|dotnet-test-explorer|formulahendry|0.7.8|
|EditorConfig|EditorConfig|0.16.4|
|githistory|donjayamanne|0.6.19|
|gitlens|eamodio|13.2.0|
|graphql-for-vscode|kumar-harsh|1.15.3|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.7|
|lit-html|bierner|1.11.1|
|LiveServer|ritwickdey|5.7.9|
|markdown-preview-github-styles|bierner|1.0.1|
|mermaid-markdown-syntax-highlighting|bpruitt-goddard|1.5.0|
|nunjucks|ronnidc|0.3.1|
|postcss|csstools|1.0.9|
|powershell|ms-vscode|2023.1.0|
|prettier-vscode|esbenp|9.10.4|
|remote-wsl|ms-vscode-remote|0.72.0|
|test-adapter-converter|ms-vscode|0.1.6|
|user-secrets|adrianwilczynski|2.0.1|
|volar|Vue|1.0.24|
|vscode-azureresourcegroups|ms-azuretools|0.5.6|
|vscode-docker|ms-azuretools|1.23.3|
|vscode-drawio|hediet|1.6.6|
|vscode-eslint|dbaeumer|2.2.6|
|vscode-filesize|mkxml|3.1.0|
|vscode-icons|vscode-icons-team|12.2.0|
|vscode-less|mrmlnc|0.6.3|
|vscode-markdownlint|DavidAnson|0.49.0|
|vscode-mermaid-preview|vstirbu|1.6.3|
|vscode-mysql|formulahendry|0.4.1|
|vscode-scss|mrmlnc|0.10.0|
|vscode-sqlite|alexcvzz|0.14.1|
|vscode-stylelint|stylelint|1.2.3|
|vscode-tailwindcss|bradlc|0.9.6|
|vscode-versionlens|pflannery|1.0.14|
|vscode-xml|redhat|0.23.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|
|vsliveshare|ms-vsliveshare|1.0.5823|;

</details>

**Comment by kirse** [comment]
Can confirm that downgrading to C# extension `v1.25.2` fixes this for now.  dotnet `6.0.300` and VSCode:
```
Version: 1.73.1 (system setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

**Comment by h4n0** [comment]
Same issue here. Downgrading to `1.25.2` fixes my issue.

**Comment by brokelyn** [comment]
I have the same issue with the latest version `1.25.4`
Downgrading and applying the above described fixes works but would be nice to have a fix for that in the next version.

**Comment by dibarbet** [comment]
@allisonchou @davidwengier FYI

**Comment by PeteX** [comment]
The workaround only helps if you are using a Linux distro which still includes OpenSSL 1.1.1, and many of them don't.  I think I have a different workaround, but it's a bit weird... 

First of all, downgrade to `1.25.2` as other posters have suggested.  Now go to the directory where the extension is installed, probably `~/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64`.  In there you will find two directories, one called `.razor` and one called `.debugger`.  Both of these directories contain a file called `libSystem.Security.Cryptography.Native.OpenSsl.so` but they are different.

Copy the file from `.debugger` to `.razor`.

To be honest I'm really surprised this works, but it currently seems to be okay on my system.  I'll post again if I wake up and find it's not working. 😊

I hope we can have a proper fix for this soon—are you (Microsoft) able to reproduce this, and do you need any more information from us?

**Comment by keefer1707** [comment]
This is actually starting to drive me up the wall.  Every time I paste in code, or save a file, I get the same error.  I'm going to disable formatting for razor files for now.  Can also confirm downgrade to v1.25.2 removes the error.

If it helps, I captured some Razor Log below.  First, I cleared the log output, then pasted some HTML code to trigger the error.  The following log was generated:

```
[Client - 10:28:07 PM] Updating the HTML document for Razor file 'c:/Projects/FDMWeb/FDMWeb/Views/Personnel/_WCBInjuries.cshtml' (565)
[Client - 10:28:07 PM] Notifying document 'c:\Projects\FDMWeb\FDMWeb\Views\Personnel\_WCBInjuries.cshtml' changed 'htmlChanged'
[Client - 10:28:07 PM] Updating the C# document for Razor file 'c:/Projects/FDMWeb/FDMWeb/Views/Personnel/_WCBInjuries.cshtml' (565)
[Client - 10:28:07 PM] Notifying document 'c:\Projects\FDMWeb\FDMWeb\Views\Personnel\_WCBInjuries.cshtml' changed 'csharpChanged'
[Error - 10:28:07 PM] [null]
[Error - 10:28:07 PM] Request textDocument/rangeFormatting failed.
  Message: Specified argument was out of the range of valid values. (Parameter 'Range start line 131 matches or exceeds SourceText boundary 131.')
  Code: -32000 
[object Object]
```

Environment Info
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

C# Extension v1.25.4

**Comment by davidwengier** [comment]
This was fixed by https://github.com/dotnet/razor/pull/8318

**Comment by ImRLopezAG** [comment]
> Same issue here. Downgrading to `1.25.2` fixes my issue.

Same issuse, This works, Downgrading to `1.25.2` fixes my issue.

**Comment by abdollahkahne** [comment]
I have this issue but suddenly after updating my visual Code, errors and warning removed and my razor pages work like last good days. The other thing I changed which may be important is that, I realized that already Visual Studio knows by default that which formatter (OmniSharp C# or Prettier) it should apply according to file format. So I reset all my user and workspace (an folder) setting regarded to format to default (except format on Save tick). This altough seems unrelated but that may work for you. I am using VS Code Version 1.76.0 and C# for Visual Studio Code (powered by OmniSharp).
V 1.25.4

**Comment by PeteX** [comment]
I'm not sure if it's clear from the comments, but this issue is still a nuisance.  It's possible to get an old version of the C#/Razor extension working using the work-around I described earlier, but it has other bugs which are probably fixed in the later release.

I was wondering if we can expect a new release of the extension soon, given that the problem is evidently fixed in the current sources.

Many thanks for your work on this, and I do understand if it's difficult to do a release straight away because of other priorities.

**Comment by gmkado** [comment]
If anyone is coming here looking for a fix, `1.25.5` is not in the  extensions marketplace yet but you can install it by following the instructions here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by tkoenig89** [comment]
@gmkado did 1.25.5 work for you? I installed it a few minutes ago (+ restarted VS Code) and i still get the formatting error message with the log showing this:

```
Entering method textDocument/formatting.
[Error - 7:21:17 AM] [null]
[Error - 7:21:17 AM] Request textDocument/formatting failed.
  Message: Specified argument was out of the range of valid values. (Parameter 'Range end line 26 matches or exceeds SourceText boundary 26.')
  Code: -32000 
[object Object]
```

**VS Code** v1.77.3
**C# Ext.** 1.25.5 via VSIX
**.Net** 7.0.103

**Comment by tkoenig89** [comment]
Adding to the above:

I just installed the latest .Net 7 SDK (7.0.203) and created a new project (`dotnet new mvc`). Trying to format any of the default `.cshtml` Razor files causes the same error message.

@davidwengier as you closed this as fixed, is there anything wrong with my setup or is this bug just not actually fixed?

**Comment by davidwengier** [comment]
The bug is fixed, but we have not been able to ship a new version of the extension with the fix in it. Unfortunately the process is not straight forward.

**Comment by gmkado** [comment]
@tkoenig89 it has been working for me so far.  My versions:
VS Code v1.77.2
C# Ext. 1.25.5 via VSIX
.Net 6.0.401

**Comment by tkoenig89** [comment]
> @tkoenig89 it has been working for me so far. My versions: VS Code v1.77.2 C# Ext. 1.25.5 via VSIX .Net 6.0.401

Thanks. It might be an issue with .Net 7. As the initial issue appeared months ago when we upgraded .Net 6 to .Net 7.

**Comment by abdollahkahne** [comment]
> and warning removed and my razor pages work like last good days. The other thing I changed which may be important is that, I realized that already Visual Studio knows by default that which formatter (OmniSharp C# or Prettier) it should apply according to file format. So I reset all my user and workspace (an folder) setting regarded to format to default (except format on Save tick). This altough seems unrelate

I test this in my new installation with .Net 7 and it does not work. Apparently something else I had changed!!

**Comment by PeteX** [comment]
I've just tried the beta, and I think it might be a bit better, but there is still at least one case where it fails.  If I choose `Format Document` I get the same error, `Request textDocument/formatting failed.`  The output window display this:

```
Entering method textDocument/formatting.
[Error - 18:25:58] [null]
[Error - 18:25:58] Request textDocument/formatting failed.
  Message: Specified argument was out of the range of valid values. (Parameter 'Range end line 14 matches or exceeds SourceText boundary 14.')
  Code: -32000 
[object Object]
```

Thanks for looking into this for us.

**Comment by allisonchou** [comment]
@PeteX do you have a set of repro steps you could share for the case that fails? I'm not able to repro on my end but would like to dig into the issue further.

**Comment by PeteX** [comment]
This does it for me @allisonchou:

1. Create a new project: `dotnet new blazorserver -o Test`
2. `cd Test`
3. `code .`
4. Open `Pages/Counter.razor`
5. Right-click menu, then `Format Document`.

I hope this works for you too, very annoying when it's difficult reproducing issues! 🙂 I'm on Linux by the way, Ubuntu 22.04, KDE.  VSCode is 1.77.3, the official build.

**Comment by PeteX** [comment]
Oh here is a bit more info which might be useful:

```
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.15.0-70-generic
Sandboxed: No
```

**Comment by abdollahkahne** [comment]
Error exist yet 
![image](https://user-images.githubusercontent.com/48277995/233827266-0625b6a7-08cf-46bd-9040-85fdeca4b04b.png)
I am using visual code debian version on linux ubuntu with dotnet 7 and last beta version downloaded following link
[Vsix file](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.25.6)

**Comment by abdollahkahne** [comment]
## Is this a Bug or Feature request?:
Bug

## Steps to reproduce
------------------- Please fill in this section -------------------------

## Description of the problem:
------------------- Please fill in this section -------------------------

Expected behavior:

Actual behavior:

## Logs

#### OmniSharp
------------------- Please fill in this section -------------------------
To find the OmniSharp log, open VS Code's "Output" pane, then in the dropdown choose "OmniSharp Log".

#### Razor
<details><summary>Expand</summary>
<p>

```
[Client - 11:31:46] -- Starting Issue Data Collection-- 
[Client - 11:31:50] (Warning) provideCodeLens failed with Error: command 'razor/runCodeAction' already exists
[Client - 11:31:55] -- Stopping Issue Data Collection-- 
```

</p>
</details>

## Workspace information

#### Razor document:
<details><summary>Expand</summary>
<p>

```Razor

@model PersonViewModel
@{
    ViewData["Title"]="Person Details";
}

<div class="display-info">
    <div class="form-container">
        <div class="item-main">
            <h4 class="text-center"><span>@Model.FirstName @Model.LastName</span></h4>
            
            <div>
                 <b>National Id:</b> <span>@Model.NationalId</span>
            </div>
   
        </div>
        <div class="item-details">
             <ul>
        @foreach (var item in Model.UniversityLines)
        {
            <li>
                @item.Level of @item.Major (with speciality in @item.Minor) from @item.University?.Name (@item.University.Type) with GPA @item.GPA (between @item.StartDate - @item.EndDate)<br/>
                University Address: @item.University.Address
            </li>
        }
    </ul>
        </div>
        
    </div>

</div>

```

</p>
</details>

#### Projected CSharp document:
<details><summary>Expand</summary>
<p>

```C#
////////////////////// Projected CSharp as seen by extension ///////////////////////
// <auto-generated/>
#pragma warning disable 1591
namespace AspNetCore
{
    #line hidden
    using TModel = global::System.Object;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/_ViewImports.cshtml"
using MVCSample;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/_ViewImports.cshtml"
using MVCSample.Models;

#line default
#line hidden
#nullable disable
    #nullable restore
    public class Views_People_Display : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<PersonViewModel>
    #nullable disable
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((global::System.Action)(() => {
#nullable restore
#line 2 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
PersonViewModel __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 3 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
  
    ViewData["Title"]="Person Details";

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                     __o = Model.FirstName;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                      __o = Model.LastName;

#line default
#line hidden
#nullable disable
#nullable restore
#line 13 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                      __o = Model.NationalId;

#line default
#line hidden
#nullable disable
#nullable restore
#line 19 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
         foreach (var item in Model.UniversityLines)
        {
            

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
           __o = item.Level;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                          __o = item.Major;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                          __o = item.Minor;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                            __o = item.University?.Name;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                    __o = item.University.Type;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                    __o = item.GPA;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                                       __o = item.StartDate;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                                                         __o = item.EndDate;

#line default
#line hidden
#nullable disable
#nullable restore
#line 23 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                               __o = item.University.Address;

#line default
#line hidden
#nullable disable
#nullable restore
#line 24 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                 
        }

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<PersonViewModel> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
// <auto-generated/>
#pragma warning disable 1591
namespace AspNetCore
{
    #line hidden
    using TModel = global::System.Object;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/_ViewImports.cshtml"
using MVCSample;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/_ViewImports.cshtml"
using MVCSample.Models;

#line default
#line hidden
#nullable disable
    #nullable restore
    public class Views_People_Display : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<PersonViewModel>
    #nullable disable
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((global::System.Action)(() => {
#nullable restore
#line 2 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
PersonViewModel __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 3 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
  
    ViewData["Title"]="Person Details";

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                     __o = Model.FirstName;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                      __o = Model.LastName;

#line default
#line hidden
#nullable disable
#nullable restore
#line 13 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                      __o = Model.NationalId;

#line default
#line hidden
#nullable disable
#nullable restore
#line 19 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
         foreach (var item in Model.UniversityLines)
        {
            

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
           __o = item.Level;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                          __o = item.Major;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                          __o = item.Minor;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                            __o = item.University?.Name;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                    __o = item.University.Type;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                    __o = item.GPA;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                                       __o = item.StartDate;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                                                         __o = item.EndDate;

#line default
#line hidden
#nullable disable
#nullable restore
#line 23 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                               __o = item.University.Address;

#line default
#line hidden
#nullable disable
#nullable restore
#line 24 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                 
        }

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<PersonViewModel> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591



////////////////////// Projected CSharp as seen by VSCode ///////////////////////
// <auto-generated/>
#pragma warning disable 1591
namespace AspNetCore
{
    #line hidden
    using TModel = global::System.Object;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/_ViewImports.cshtml"
using MVCSample;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/_ViewImports.cshtml"
using MVCSample.Models;

#line default
#line hidden
#nullable disable
    #nullable restore
    public class Views_People_Display : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<PersonViewModel>
    #nullable disable
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((global::System.Action)(() => {
#nullable restore
#line 2 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
PersonViewModel __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 3 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
  
    ViewData["Title"]="Person Details";

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                     __o = Model.FirstName;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                      __o = Model.LastName;

#line default
#line hidden
#nullable disable
#nullable restore
#line 13 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                      __o = Model.NationalId;

#line default
#line hidden
#nullable disable
#nullable restore
#line 19 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
         foreach (var item in Model.UniversityLines)
        {
            

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
           __o = item.Level;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                          __o = item.Major;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                          __o = item.Minor;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                            __o = item.University?.Name;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                    __o = item.University.Type;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                    __o = item.GPA;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                                       __o = item.StartDate;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                                                         __o = item.EndDate;

#line default
#line hidden
#nullable disable
#nullable restore
#line 23 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                               __o = item.University.Address;

#line default
#line hidden
#nullable disable
#nullable restore
#line 24 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                 
        }

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<PersonViewModel> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
// <auto-generated/>
#pragma warning disable 1591
namespace AspNetCore
{
    #line hidden
    using TModel = global::System.Object;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/_ViewImports.cshtml"
using MVCSample;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/_ViewImports.cshtml"
using MVCSample.Models;

#line default
#line hidden
#nullable disable
    #nullable restore
    public class Views_People_Display : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<PersonViewModel>
    #nullable disable
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((global::System.Action)(() => {
#nullable restore
#line 2 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
PersonViewModel __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 3 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
  
    ViewData["Title"]="Person Details";

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                     __o = Model.FirstName;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                      __o = Model.LastName;

#line default
#line hidden
#nullable disable
#nullable restore
#line 13 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                      __o = Model.NationalId;

#line default
#line hidden
#nullable disable
#nullable restore
#line 19 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
         foreach (var item in Model.UniversityLines)
        {
            

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
           __o = item.Level;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                          __o = item.Major;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                          __o = item.Minor;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                            __o = item.University?.Name;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                    __o = item.University.Type;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                    __o = item.GPA;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                                       __o = item.StartDate;

#line default
#line hidden
#nullable disable
#nullable restore
#line 22 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                                                                                                                                                                         __o = item.EndDate;

#line default
#line hidden
#nullable disable
#nullable restore
#line 23 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                               __o = item.University.Address;

#line default
#line hidden
#nullable disable
#nullable restore
#line 24 "/home/anonymous/Desktop/Samples/Pegah/MVCSample/Views/People/Display.cshtml"
                 
        }

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<PersonViewModel> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591

// 2
```

</p>
</details>

#### Projected Html document:
<details><summary>Expand</summary>
<p>

```Html
////////////////////// Projected Html as seen by extension ///////////////////////

~~~~~~ ~~~~~~~~~~~~~~~
~~
    ~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~
~

<div class="display-info">
    <div class="form-container">
        <div class="item-main">
            <h4 class="text-center"><span>~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~</span></h4>
            
            <div>
                 <b>National Id:</b> <span>~~~~~~~~~~~~~~~~~</span>
            </div>
   
        </div>
        <div class="item-details">
             <ul>
        ~~~~~~~~ ~~~~ ~~~~ ~~ ~~~~~~~~~~~~~~~~~~~~~~
        ~
            <li>
                ~~~~~~~~~~~ of ~~~~~~~~~~~ (with speciality in ~~~~~~~~~~~) from ~~~~~~~~~~~~~~~~~~~~~~ (~~~~~~~~~~~~~~~~~~~~~) with GPA ~~~~~~~~~ (between ~~~~~~~~~~~~~~~ - ~~~~~~~~~~~~~)<br/>
                University Address: ~~~~~~~~~~~~~~~~~~~~~~~~
            </li>
        ~
    </ul>
        </div>
        
    </div>

</div>

~~~~~~ ~~~~~~~~~~~~~~~
~~
    ~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~
~

<div class="display-info">
    <div class="form-container">
        <div class="item-main">
            <h4 class="text-center"><span>~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~</span></h4>
            
            <div>
                 <b>National Id:</b> <span>~~~~~~~~~~~~~~~~~</span>
            </div>
   
        </div>
        <div class="item-details">
             <ul>
        ~~~~~~~~ ~~~~ ~~~~ ~~ ~~~~~~~~~~~~~~~~~~~~~~
        ~
            <li>
                ~~~~~~~~~~~ of ~~~~~~~~~~~ (with speciality in ~~~~~~~~~~~) from ~~~~~~~~~~~~~~~~~~~~~~ (~~~~~~~~~~~~~~~~~~~~~) with GPA ~~~~~~~~~ (between ~~~~~~~~~~~~~~~ - ~~~~~~~~~~~~~)<br/>
                University Address: ~~~~~~~~~~~~~~~~~~~~~~~~
            </li>
        ~
    </ul>
        </div>
        
    </div>

</div>



////////////////////// Projected Html as seen by VSCode ///////////////////////

~~~~~~ ~~~~~~~~~~~~~~~
~~
    ~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~
~

<div class="display-info">
    <div class="form-container">
        <div class="item-main">
            <h4 class="text-center"><span>~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~</span></h4>
            
            <div>
                 <b>National Id:</b> <span>~~~~~~~~~~~~~~~~~</span>
            </div>
   
        </div>
        <div class="item-details">
             <ul>
        ~~~~~~~~ ~~~~ ~~~~ ~~ ~~~~~~~~~~~~~~~~~~~~~~
        ~
            <li>
                ~~~~~~~~~~~ of ~~~~~~~~~~~ (with speciality in ~~~~~~~~~~~) from ~~~~~~~~~~~~~~~~~~~~~~ (~~~~~~~~~~~~~~~~~~~~~) with GPA ~~~~~~~~~ (between ~~~~~~~~~~~~~~~ - ~~~~~~~~~~~~~)<br/>
                University Address: ~~~~~~~~~~~~~~~~~~~~~~~~
            </li>
        ~
    </ul>
        </div>
        
    </div>

</div>

~~~~~~ ~~~~~~~~~~~~~~~
~~
    ~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~
~

<div class="display-info">
    <div class="form-container">
        <div class="item-main">
            <h4 class="text-center"><span>~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~</span></h4>
            
            <div>
                 <b>National Id:</b> <span>~~~~~~~~~~~~~~~~~</span>
            </div>
   
        </div>
        <div class="item-details">
             <ul>
        ~~~~~~~~ ~~~~ ~~~~ ~~ ~~~~~~~~~~~~~~~~~~~~~~
        ~
            <li>
                ~~~~~~~~~~~ of ~~~~~~~~~~~ (with speciality in ~~~~~~~~~~~) from ~~~~~~~~~~~~~~~~~~~~~~ (~~~~~~~~~~~~~~~~~~~~~) with GPA ~~~~~~~~~ (between ~~~~~~~~~~~~~~~ - ~~~~~~~~~~~~~)<br/>
                University Address: ~~~~~~~~~~~~~~~~~~~~~~~~
            </li>
        ~
    </ul>
        </div>
        
    </div>

</div>

// 2
```

</p>
</details>

## Machine information


**VSCode version**: 1.77.3
**Razor.VSCode version**: 1.25.6
#### `dotnet --info`

<details><summary>Expand</summary>
<p>

```
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.203/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.203 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

</p>
</details>

#### Extensions
<details><summary>Expand</summary>
<p>


|Extension|Author|Version|
|---|---|---|
|asp-net-core-switcher|adrianwilczynski|2.0.2|
|blazor-snippet-pack|adrianwilczynski|2.6.1|
|csharp|ms-dotnettools|1.25.6|
|csharpextensions|kreativ-software|1.7.3|
|docomment|k--kato|1.0.0|
|prettier-vscode|esbenp|9.12.0|
|razor-switcher|LennartKleymann|1.0.0|
|rest-client|humao|0.25.1|
|test-adapter-converter|ms-vscode|0.1.7|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-resx-editor|DominicVonk|0.0.5|;


</p>
</details>

**Comment by abdollahkahne** [comment]
I downgraded to 1.25.2 and it works for me for now.

**Comment by tkoenig89** [comment]
As both examples above are running linux, here is my setup on windows causing the same issue on a new `dotnet new razor/mvc` project.

C#-Extensions 1.25.6
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by PeteX** [comment]
Hello, I've just tried the 1.25.7 release.  I'm not sure if that release was intended to have a fix for this issue, but it made no difference for me.  The reproduction steps at https://github.com/OmniSharp/omnisharp-vscode/issues/5561#issuecomment-1518364826 still give the same errors.

**Comment by jeremy-farrance** [comment]
I wouldn't call this conclusive, but I just uninstalled and manually installed 1.25.7 _and the errors are gone for me._

C# Ext v1.25.7

Version: 1.77.3 (system setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by PeteX** [comment]
I just tried again, installing from the Marketplace this time, and it's still not working for me—how annoying.  The only difference I can see is that I'm on Linux, but I don't see why that should change anything.

@jeremy-farrance if you wouldn't mind, could you try the repro steps I posted at https://github.com/OmniSharp/omnisharp-vscode/issues/5561#issuecomment-1518364826 ?  That still fails for me, so it would be interesting to know if it now works for you.  Many thanks (and if you don't have time, don't worry about it).

**Comment by dibarbet** [comment]
I don't expect the latest release to resolve all the formatting issues - it is still being worked on

**Comment by seangwright** [comment]
I just
- uninstalled the C# extension (and all the ones that depended on it)
- closed VS Code
- reopened VS Code
- reinstalled the C# extension (v1.25.7)
- opened a `.cshtml` file with valid Razor in it
- formatted the file
- saw the same `Request textDocument/formatting failed.` error

So, as far as I can tell, a normal install of the extension is still broken.

```
Version: 1.77.3 (system setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

**Comment by davidwengier** [comment]
Thanks for all of the feedback folks, I've been able to repro this, and have a PR open to fix it. Unfortunately releasing updates to the extension is a relatively slow process, so you'll have to bear with us a little longer. Sorry!

**Comment by PeteX** [comment]
I just tried the pre-release, and it looks as though the problem is fixed!  Thank you for all your hard work on this.

**Comment by garrettlondon1** [comment]
<img width="826" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/3959577/e50ae44a-1cee-4d78-a405-e6ca5cb4afbe">

Still having the issue with pre-release version.

[Error - 5:19:06 PM] Request textDocument/semanticTokens/range failed.
  Message: Value cannot be null. (Parameter 'DocumentContext')
  Code: -32000 
[object Object]
[Error - 5:19:39 PM] System.ArgumentNullException: Value cannot be null. (Parameter 'DocumentContext')
   at Microsoft.AspNetCore.Razor.LanguageServer.EndpointContracts.RazorRequestContext.GetRequiredDocumentContext() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorRequestContext.cs:line 29
   at Microsoft.AspNetCore.Razor.LanguageServer.Semantic.SemanticTokensRangeEndpoint.HandleRequestAsync(SemanticTokensRangeParams request, RazorRequestContext requestContext, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/SemanticTokensRangeEndpoint.cs:line 75
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
[Error - 5:19:39 PM] Request textDocument/semanticTokens/range failed.
  Message: Value cannot be null. (Parameter 'DocumentContext')
  Code: -32000 
[object Object]

**Comment by davidwengier** [comment]
@garrettlondon1  that error appears to come from the semantic tokens system, which is different from formatting, and is coming from the Razor LSP server. Would you might logging it as an issue on https://github.com/dotnet/razor. You should be able to use the Report an Issue feature of the extension, which will include logs and version info etc.

**Comment by DaveMcCrady** [comment]
This happens with every edit of a .cshtml file.
C# extension 2.0.357

Version: 1.81.0 (Universal)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:40:02.782Z (1 wk ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

<TargetFramework>net6.0</TargetFramework>

dotnet --list-sdks
6.0.100 [/usr/local/share/dotnet/sdk]
6.0.412 [/usr/local/share/dotnet/sdk]

**Entering method textDocument/formatting.
[Error - 11:37:45 AM] [null]
[Error - 11:37:45 AM] Request textDocument/formatting failed.
  Message: Specified argument was out of the range of valid values. (Parameter 'Range end line 65 matches or exceeds SourceText boundary 65.')
  Code: -32000 
[object Object]
Entering method textDocument/didSave.
[Info  - 11:37:45 AM] Saved Document**

It is super annoying...  
Any / all recommendations welcome.

**Comment by garrettlondon1** [comment]
```
[Error - 3:43:54 PM] Request textDocument/formatting failed.
  Message: Specified argument was out of the range of valid values. (Parameter 'Range start line 116 matches or exceeds SourceText boundary 114.')
  Code: -32000 

```
Latest version of C# extension for VS code. @davidwengier I don't think this is fixed. Given 14 people now have liked the above comment, I don't think this should be "Closed"

**Comment by DaveMcCrady** [comment]
@garrettlondon1 , this seems to be resolved for me as of today tbh.  No mention in the change log, but 2.5.30 seems to work, fingers crossed.

Extension Version 2.5.30 
VSCode Version: 1.82.2 (Universal)

**Comment by davidwengier** [comment]
@garrettlondon1 it's a very subtle difference, but it looks like you're running into a different scenario from the original report.

The error originally reported, and the one the PR fixed, is when the error message says "Range start line X matches or exceeds SourceText boundary X", where the two line numbers "X" were both the same. This was because we had a bug where we weren't honouring the LSP spec which allows the end point of a in a formatting request to be past the end of the document. Essentially our API (SourceText) was an inclusive end, and LSP was exclusive.

The error you're hitting has two different numbers in it, and they're off by 2, which implies something else is going on. If it is possible for you to provide an example project or file where this happens, that would be ideal, and its probably easier to log a new issue for it so we can track it easier.

**Comment by garrettlondon1** [comment]
Thanks @davidwengier, that is a subtle difference indeed. I can PM you an example razor file where on format I get the same error. I will log a new issue

**Comment by DaveMcCrady** [comment]
@davidwengier 
Unfortunately, I am receiving this error after pasting code into the file.  (Extension Version: v2.5.30)
[Error - 11:37:15 AM] Request textDocument/rangeFormatting failed.
  Message: Specified argument was out of the range of valid values. (Parameter 'Range end line 29 matches or exceeds SourceText boundary 29.')
  Code: -32000 
[object Object]

Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0

**Comment by davidwengier** [comment]
@DaveMcCrady when it happens, could you run the "Show Razor Html" command and see if the generated Html looks reasonable? You'll see all C# code replaced with `~` characters, so it will look weird, but the crucial piece of information is whether there is a duplicate copy of the file in the generated Html. If so, I think you're running into an existing problem that I am looking into

**Comment by DaveMcCrady** [comment]
> @DaveMcCrady when it happens, could you run the "Show Razor Html" command and see if the generated Html looks reasonable? You'll see all C# code replaced with `~` characters, so it will look weird, but the crucial piece of information is whether there is a duplicate copy of the file in the generated Html. If so, I think you're running into an existing problem that I am looking into

@davidwengier, done but I don't see any duplicates, where would they be?

This is a new project created with "dotnet new mvc"
https://github.com/dotnet/vscode-csharp/assets/10856073/3d6875c4-e32f-4a3e-b19d-3f34b360bbec

**Comment by davidwengier** [comment]
Thanks @DaveMcCrady, I'm not seeing any duplicates either. One last question, are you using LF or CRLF line endings? We've had issues in the past with line endings, and it could be a reason I'm not repro-ing things.

**Comment by arhoads76** [comment]
I have two .cshtml files where one has the error and the other does not. I copied the entire contents of the one that did not have the error to the one that did have the error, and it continued to have the error. It leads me to conclude it is not related to code or linefeeds.

**Comment by arhoads76** [comment]
Actually, I'm seeing that all of my Index.cshtml files have the error, and none of the rest of my .cshtml files have the error. In fact, if I take one of my Index.cshtml files and rename it to something else, the error goes away.

**Comment by arhoads76** [comment]
Nuts, my apologies, I've been tracking two threads, but my error is "Request textDocument/semanticTokens/range" not "Request textDocument/formatting failed". Sorry.
