### ISSUE TITLE
Custom Roslyn code fix providers not suggested as quick fix actions

### ISSUE THREAD

**Issue by achobanov** [OmniSharp/omnisharp-vscode#7802]
Type: <b>Bug</b>

## Issue Description ##
They work as expected in VS and they were working for a few days on VS Code, but now they are no longer suggested.

## Steps to Reproduce ##
Not sure what's changed since they stopped working. I did convert to pre-release versions of c# and c# dev kit at some point in order to test something unrelated, but I restored to stable versions afterwards. I've made no changes do my fix providers since it was working (and it's currently working in VS as mentioned)

## Expected Behavior ##
Code fix actions should be provided in the quick fix menu

## Actual Behavior ##
They aren't

## Logs ##

[exthost.zip](https://github.com/user-attachments/files/17787482/exthost.zip)

## Environment information ##

**VSCode version**: 1.93.1
**C# Extension**: 2.55.29
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.e0880c5d
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.403\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [android]
   Installation Source: SDK 8.0.400, VS 17.11.35327.3
   Manifest Version:    34.0.143/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.143\WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: SDK 8.0.400, VS 17.11.35327.3
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 8.0.400, VS 17.11.35327.3
   Manifest Version:    18.0.8303/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\18.0.8303\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: SDK 8.0.400, VS 17.11.35327.3
   Manifest Version:    18.0.8303/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\18.0.8303\WorkloadManifest.json
   Install Type:        FileBased

 [maui-windows]
   Installation Source: SDK 8.0.400, VS 17.11.35327.3
   Manifest Version:    8.0.82/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.82\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  6.0.419 [C:\Program Files\dotnet\sdk]
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.201 [C:\Program Files\dotnet\sdk]
  8.0.302 [C:\Program Files\dotnet\sdk]
  8.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|auto-close-tag|formulahendry|0.5.15|formulahendry.auto-close-tag-0.5.15|
|csdevkit|ms-dotnettools|1.13.9|ms-dotnettools.csdevkit-1.13.9-win32-x64|
|csharp|ms-dotnettools|2.55.29|ms-dotnettools.csharp-2.55.29-win32-x64|
|markdown-preview-github-styles|bierner|2.1.0|bierner.markdown-preview-github-styles-2.1.0|
|razor-switcher|LennartKleymann|1.0.0|lennartkleymann.razor-switcher-1.0.0|
|vscode-dotnet-runtime|ms-dotnettools|2.2.3|ms-dotnettools.vscode-dotnet-runtime-2.2.3|
|vscode-github-actions|github|0.27.0|github.vscode-github-actions-0.27.0|
|vscode-icons|vscode-icons-team|12.9.0|vscode-icons-team.vscode-icons-12.9.0|
|vscode-todo-highlight|wayou|1.0.5|wayou.vscode-todo-highlight-1.0.5|
|vscode-yaml|redhat|1.15.0|redhat.vscode-yaml-1.15.0|
|vscodeintellicode-csharp|ms-dotnettools|2.2.3|ms-dotnettools.vscodeintellicode-csharp-2.2.3-win32-x64|;

</details>

Extension version: 2.55.29
VS Code version: Cursor 0.42.5 (001668006cc714afd397f4ef0d52862f5a095530, 2024-11-14T00:33:36.512Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (13.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

Sorry to pepper you with issues, hope my logs help. If you need further information I'm happy to help.

**Comment by dennitorf** [comment]
Same issue, MacOS Sequoia 15.1, dot net 8.0.104.

**Comment by dibarbet** [comment]
@achobanov @dennitorf would either of you mind trying 2.56.31 (prerelease)?  There is a related fix in that version that might also fix code actions.

**Comment by achobanov** [comment]
I'll check it out at the weekend.

**Comment by jsgraham** [comment]
I think I'm having the same issue. I installed the StyleCop analyzers, and while I could see the red squiggles for violations, there were no fixes suggested. Updating to the pre-release C# extension (2.57.28) brought the quick fixes back.

**Comment by dennitorf** [comment]
I have tried the pre-release version, and the issue is not fixed. I'll retry, and keep an eye on the behaviour. Thanks.

**Comment by dibarbet** [comment]
> I have tried the pre-release version, and the issue is not fixed. I'll retry, and keep an eye on the behaviour. Thanks.

Are you able to share the code fix providers that you're using (e.g. is it a public nuget)?

**Comment by achobanov** [comment]
You can see mine [here](https://github.com/Not-Endurance/not-timing-system/blob/develop/analyzers/src/Not.Analyzers/Rules/MemberSpacing/MemberSpacingCodeFixProvider.cs). I think it was this one that didn't execute last time. I can double in a few days time.

**Comment by dibarbet** [comment]
> You can see mine [here](https://github.com/Not-Endurance/not-timing-system/blob/develop/analyzers/src/Not.Analyzers/Rules/MemberSpacing/MemberSpacingCodeFixProvider.cs). I think this one was among those that didn't execute last time. I can double in a few days time.

Thanks - I checked it out and confirmed the action was missing in 2.55 (release), but is present in 2.57.28 (current prerelease).
![Image](https://github.com/user-attachments/assets/21713cea-0de2-4936-8c8c-cf95e25240f2)

**Comment by achobanov** [comment]
@dibarbet It's working for me now, however I'd like to get a bit more time with it as the fixes were previously suggested to me and then suddenly vanished. What was the cause of the issue fixed in the prerelease? 

I'm currently on `v2.57.28 (pre-release)`

**Comment by dibarbet** [comment]
> [@dibarbet](https://github.com/dibarbet) It's working for me now, however I'd like to get a bit more time with it as the fixes were previously suggested to me and then suddenly vanished. What was the cause of the issue fixed in the prerelease?

The analyzer references containing code actions were not being included at all due to a bug when reading them on .NET core (as compared to framework in VS).

Additionally, in VSCode version 1.95.0 there was a bug where the lightbulb would not show code actions if the provider took longer than 1.5 seconds.  That has since been fixed in higher versions (1.95.3 being the latest)

**Comment by PedroContipelli** [comment]
Still have this issue on latest version. No quick fixes show up for me. Running VSCode in WSL and a .NET 8 project
