### ISSUE TITLE
Omnisharp does not display all errors/warnings in VSCode

### ISSUE THREAD

**Issue by HalfVoxel** [OmniSharp/omnisharp-vscode#812]
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version:
1.6.0

C# Extension version:
1.4.1
## Steps to reproduce

Open a project with several errors/warnings in it (a project that you can replicate this bug in is available upon request).
## Expected  behavior

Omnisharp displays all errors/warnings in the Problems window in VSCode
## Actual behavior

Omnisharp only displays a few or no messages even though in the omnisharp log I can clearly see them and have verified that they are valid errors/warnings (or... at least sometimes the log contains all warnings/errors, sometimes it does not). I have uploaded my omnisharp log [here](http://arongranberg.com/tmp/paste_omnisharp.txt).
This is in a clean install with no other extensions. The project is a Unity project, but I doubt that should matter.

VSCode also logs "Some projects have trouble loading. Please review the output for more details." however I cannot see anything suspicious in the log even with verbose logging enabled. Though it is pretty large so I might have missed something.

Restarting VSCode or the Omnisharp server does not solve it.

I have not tried to reduce my project to a smaller size and checked if it still happens, but I am more than happy to share my project with anyone to try to debug it.

For a while it would simply display one or sometimes a few warnings (I was fixing a lot of unused 'using' declarations) and I had to fix the single warning that was displayed, wait while it re-processed everything and then fix the next warning that would then show up.

**Comment by DustinCampbell** [comment]
Hi, if this is a largeish Unity project (e.g. >= 1000 .cs source files), this is generally expected. In that case, the extension will only retrieve errors and warnings for open files to avoid constantly chewing CPU.

FYI, the link to your omnisharp log does not work me.

**Comment by HalfVoxel** [comment]
Hi

It is large, but nowhere near that large.
```
$ ls **/*.cs | wc
273
```

**Comment by HalfVoxel** [comment]
In any case, the files were open.
Huh, that's odd, it works just fine for me.

**Comment by DustinCampbell** [comment]
I'd love to take a look at your project if you're able to provide it. Perhaps we broke something. Also, you might consider trying the latest beta of the C# extension available [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-beta3) and see if that improves the issue.

**Comment by HalfVoxel** [comment]
Here are some screenshots and the log that is visible in them

![screenshot 2016-10-11 19 44 07](https://cloud.githubusercontent.com/assets/1144597/19281579/26a339ee-8feb-11e6-9b91-79dd39380be7.png)
![screenshot 2016-10-11 19 43 53](https://cloud.githubusercontent.com/assets/1144597/19281578/269514c2-8feb-11e6-9442-618b823ecb37.png)

http://pastebin.com/Us51C8Us

**Comment by HalfVoxel** [comment]
> Also, you might consider trying the latest beta of the C# extension available here and see if that improves the issue.

Ok, is it possible to install that from within VSCode or do I have to do some manual work here? (this is literally the first time I have tried using VSCode, so I am not very familiar with how the plugins work yet).

I will send you an email.

**Comment by DustinCampbell** [comment]
FWIW, the warnings in the log are produced when OmniSharp uses MSBuild to perform a design-time compilation of your project in order to gather up source files and references. However, OmniSharp does not return those. There's a separate endpoint that requires errors and warnings live from your code.

**Comment by DustinCampbell** [comment]
> Ok, is it possible to install that from within VSCode or do I have to do some manual work here? (this is literally the first time I have tried using VSCode, so I am not very familiar with how the plugins work yet).

You can install it within VS Code. Go to the Extensions pane, click the three dots at the top-right of the pane and select "Install from VSIX..."

**Comment by HalfVoxel** [comment]
> FWIW, the warnings in the log are produced when OmniSharp uses MSBuild to perform a design-time compilation of your project in order to gather up source files and references. However, OmniSharp does not return those. There's a separate endpoint that requires errors and warnings live from your code.

Ok, but it is supposed to be able to get those warnings/errors from the other endpoint as well, right?

**Comment by HalfVoxel** [comment]
> You can install it within VS Code. Go to the Extensions pane, click the three dots at the top-right of the pane and select "Install from VSIX..."

Installing the beta did not seem to resolve the problem unfortunately. Here is the log for the beta version: http://pastebin.com/r7gh70Bd

**Comment by bsell93** [comment]
I think I am experiencing something similar. I attempted to install the previously mentioned beta version with no change. For me the errors show up for a second after saving and then disappear. I have a short video of it (please forgive the watermark. I found that this bug came about after updating to the just released version of VSCode (v1.6)
![omnisharp bug](https://cloud.githubusercontent.com/assets/5335177/19285251/5c438d5c-8fc7-11e6-8185-fb0edd382a42.gif)

**Comment by HalfVoxel** [comment]
@bsell93 I also saw that once. The errors were not valid however, I think it was because I had just deleted some files and Unity had not rewritten the project file, so omnisharp was logging errors about that. I don't think it is related to this issue however.

**Comment by bsell93** [comment]
I see. Yeah, I am not sure what is going on. They are definitely errors, because I intentionally made them 😁.

**Comment by shlapkoff** [comment]
I have the same problem. This happened after the update VS Code to version 1.6

**Comment by shlapkoff** [comment]
I found a solution: in v.1.5.3 all working.

https://code.visualstudio.com/updates/v1_5

**Comment by HalfVoxel** [comment]
@shlapkoff were you referring to mine or @bsell93's problem?

**Comment by bsell93** [comment]
@shlapkoff thanks! That fixed my issue!

**Comment by DustinCampbell** [comment]
I see, so this is a recent regression with 1.6? @jrieken, have you heard any other reports of the Problems pane not displaying all errors & warnings?

**Comment by HalfVoxel** [comment]
@DustinCampbell For me downgrading to 1.5.3 did not work unfortunately.
![image](https://cloud.githubusercontent.com/assets/1144597/19312452/ac88a038-9092-11e6-82f5-53ee4186cddf.png)

**Comment by HalfVoxel** [comment]
Is there anything else I could try to help you debug this issue?
Did you manage to replicate it in the project that I sent you?

**Comment by leafi** [comment]
I'm getting this constantly with a .NET core solution as of VSCode 1.6, too. Errors appear for a second, then totally disappear.

But e.g. `dotnet build` in the terminal fails because those errors are actually totally valid.

**Comment by jrieken** [comment]
@HalfVoxel Can you check the output of the developer console in VS Code? That might contain some useful data to let me understand this better/

**Comment by shlapkoff** [comment]
@HalfVoxel  I have in mind the problem @bsell93

**Comment by jrieken** [comment]
@HalfVoxel re https://github.com/OmniSharp/omnisharp-vscode/issues/812#issuecomment-253217086 - just to clarify: you see this with 1.6 and also 1.5.x? or only with 1.6?

**Comment by HalfVoxel** [comment]
@jrieken I see this with both 1.5.3 and 1.6.

**Comment by leafi** [comment]
Sounds like it's under control, but just in case:
Extensions:
EditorConfig for VS Code 0.3.3 (latest)
Nomo Dark Icon Theme 1.1.4 (latest)
ESLint 1.0.8 (latest)
C# 1.4.1 (latest)
Vim 0.3.7 (latest)

VS Code: 1.6.0, on Arch Linux x64 using visual-studio-code from the AUR, package version 1.6.0-2
(The visual-studio-code package grabs a debian/ubuntu release, strips symbols from the official binaries, and repackages them.)

Shot of developer tools on re-opening VS Code, introducing a syntax error which quickly disappears, with a bunch of tabs open:
![2016-10-13-162442_793x991_scrot](https://cloud.githubusercontent.com/assets/2166555/19355248/a0603cce-9161-11e6-8145-1aa69c301ca9.png)

Slightly cut-down (unrunnable) version of my pure C# project which shows the issue (1.7MB):
https://calpol.us/files/public/Blamalama-minim.zip

Repro:
1. Download and extract this .zip file somewhere
2. Open the root folder in VS Code. The one that contains .vscode, the one that is one level above 'src', not 'src' itself.
3. Click the little OmniSharp button in the bottom right, and change it to 'src'. (For some reason, OmniSharp just keeps saying 'Running' with the cut-down project for some reason...)
4. Introduce a syntax error in e.g. TextBox.cs. Wait a few seconds, and it then disappears.

In my recent attempt, I got no console errors doing this. _shrugs_

Above project is not open source, and is not licensed for wider distribution except in aid of fixing VS Code & Omnisharp issues. I will remove the link once this issue is solved.

If you need any help, ask.

**Comment by HalfVoxel** [comment]
> @HalfVoxel Can you check the output of the developer console in VS Code? That might contain some useful data to let me understand this better/

The developer console (assuming you mean the chrome dev tools) unfortunately logs exactly nothing. I watched it while restarting omnisharp and having a file opened which contains things it should warn about.
![image](https://cloud.githubusercontent.com/assets/1144597/19356023/a75f8ccc-916c-11e6-8ce1-55bcdfc8bf84.png)

**Comment by HalfVoxel** [comment]
Does Omnisharp actually check for those warnings at all (assigned but not used private fields)?

**Comment by leafi** [comment]
Don't think so. But my repro steps require the user to specifically introduce a syntax error; the .zip as-is is buildable.

**Comment by DustinCampbell** [comment]
@leafi: You might try the latest beta of the C# extension and see if that addresses the issue that appears in your Developer Console in the DefinitionMetadataDocumentProvider. That problem should have been fixed with https://github.com/OmniSharp/omnisharp-vscode/commit/58f7e7950222278d2126f620c2e89ca6e7907c9c.

**Comment by leafi** [comment]
@DustinCampbell: Thank you. Indeed it (1.5.0-beta3) does. This issue, the errors disappearing issue, still occurs with that build FYI.

**Comment by DustinCampbell** [comment]
Yeah, I didn't think it'd fix that issue, but it would remove some of the noise in the Developer Console.

**Comment by leafi** [comment]
What remains is: an `[Extension Host] Error: Unsupported linux platform` and a few `[Extension Host] _isHugeProject = false (0)` lines.

**Comment by DustinCampbell** [comment]
`_isHugeProject = false (0)` is harmless. That's a bit of [debugging text](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/diagnosticsProvider.ts#L100-L112) I forgot to turn off.

`Error: Unsupported linux platform` is equally harmless. That's just the debugger doing a check and determining whether it can run on the current Linux distro (you're on ArchLinux, right?). The debugger check is [here](https://github.com/OmniSharp/omnisharp-vscode/blob/745ae50aea40860c57b2befbb10a790a092ab8f4/src/coreclr-debug/activate.ts#L189).

**Comment by jrieken** [comment]
@leafi Thanks - I can repo with your sample, drilling into the cause of this now

**Comment by jrieken** [comment]
@DustinCampbell Pretty sure this is a bad equality check in the [`DiagnosticsProvider`](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/diagnosticsProvider.ts#L250) - it compares `tuple[0] === uri` which are both `vscode.Uri`s but (sadly) not triple-equals comparable. 

In the debugger, I can see how I first get a set-diagnostics call and later a clear call. 

<img width="1020" alt="screen shot 2016-10-14 at 10 33 10" src="https://cloud.githubusercontent.com/assets/1794099/19380930/c311c4e8-91f9-11e6-850d-52090fef4614.png">

**Comment by jrieken** [comment]
Obviously this doesn't answer the question why *some* people only see this on 1.6. Maybe extra awareness in the face of a new release or a side-effect from the reworked diagnostics internals on our side.

**Comment by DustinCampbell** [comment]
Thanks for the analysis @jrieken! I suspect this was just hiding under to the performance issues you fixed in this release. Now that those are gone, this has bubbled to the top.

**Comment by DustinCampbell** [comment]
FWIW, that bit of code was an attempt to try and improve performance, but I don't think it's necessary any longer with all of the diagnostics performance fixes that went into 1.6.

**Comment by leafi** [comment]
Thanks lads. Hacking my local, already-transpiled copy of the extension (in `diagnosticsProvider.js`) to remove the lines proposed by PR #820 does indeed fix the issue for me.

I look forward to getting my squigglies back on an official basis. Thanks again for looking into this.

**Comment by DustinCampbell** [comment]
@leafi: Glad to hear it!

**Comment by DustinCampbell** [comment]
[v1.5-beta4](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-beta4) of the extension is now available containing this fix.

**Comment by leafi** [comment]
File on that release is called `-beta3.vsix`

**Comment by DustinCampbell** [comment]
Sigh... it's early. :smile: Will fix shortly.

**Comment by DustinCampbell** [comment]
Fixed :smile:

**Comment by nakedpony** [comment]
Thx. v1.5-beta4 indeed fixes the issue.

**Comment by dijitalmunky** [comment]
Confirmed working for me as well!  Good job!

**Comment by masaeedu** [comment]
@DustinCampbell Not sure if I'm seeing a different issue, or this is just how its supposed to work, but I'm not seeing errors where I expect to see them. Here's what I'm doing:

 1. Set up a folder with:
   1. Multiple folders containing `project.json` files and code
   2. A global.json file with a `projects` array pointing to each proejct folder
   3. Code in one of the project folders that produces compile errors with `dotnet build`
 2. Start VS Code 1.6.1 with omnisharp-vscode 1.5-beta4 installed
 3. Open the folder containing global.json

At this point, I don't see any of the errors I see from `dotnet build` in the bottom ribbon or the "Problems" pane. 

I assumed this was because I need to somehow explicitly trigger a build through Omnisharp, but I can't find a way to do so. The only two Omnisharp related options I have available in the command palette are: "Omnisharp: Restart Omnisharp", and "Omnisharp: Select Project", and I've already used the latter to select the project containing the errors. I also tried running "Tasks: Run Build Task", but this results in the output:

> Couldn't find 'project.json' in current directory

Here's what the Omnisharp generated `tasks.json` looks like:

```
{
    "version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [],
    "tasks": [
        {
            "taskName": "build",
            "args": [
                ""
            ],
            "isBuildCommand": true,
            "problemMatcher": "$msCompile"
        }
    ]
}
```

I'd appreciate any guidance on whether I should be expecting errors to pop up as I work (and so there is a bug), or if I need to build the projects through VS Code using some approach I've missed.

The project I'm working with is a Github fork, so if this is an actual bug rather than PEBKAC, I can push up all my work and give you a link.

**Comment by aggieben** [comment]
I tried to install the 1.5-beta4 version, and this was the result:

![image](https://cloud.githubusercontent.com/assets/1321/19568210/4509451e-96b6-11e6-85e1-a7bd264870db.png)

**Comment by gregg-miskelly** [comment]
@aggieben installing .vsix's by hand is sadly pretty confusing. You can *NOT* double click them. Instead you need to open them as a file from VS Code.

**Comment by DustinCampbell** [comment]
That's right. In VS Code, select View->Extensions. Then, at the top-right of Extensions pane click the [...] and select "Install from VSIX..."

**Comment by masaeedu** [comment]
@DustinCampbell Any thoughts on my earlier comment? Is the discrepancy between `dotnet build` and the Omnisharp errors log as intended, or is there some action you need to take for Omnisharp to show you the same errors?

**Comment by DustinCampbell** [comment]
@masaeeedu: Sorry for the delay. What you described doesn't look like the same problem that everyone else was experiencing in this thread. Could you file a separate issue? Also, if you have a project that reproduces the problem, that'd be helpful too.

**Comment by aggieben** [comment]
I have the beta4 extension installed now, and after the last code update (1.6.1), this issue is manifesting again.

**Comment by matthewjcooper** [comment]
I still have this issue and I'm using VS Code 1.6.1 and Omnisharp 1.5.0-beta4. I have multiple projects with a global.json file.

**Comment by DustinCampbell** [comment]
The issue as originally filed was about .csproj/.sln on Unity projects. For any experiencing this issue on project.json, could you please file a separate issue?

**Comment by ccbentlee** [comment]
I'm using VS Code 1.6.1 and and Omnisharp 1.5.0-beta4 for my Unity project, the issue here was solved but the flame icon used to show "xxxx.sln" now says "0 projects" even through I select the .sln in the list. Other than that everything is fine.

**Comment by Novack-** [comment]
Today installed 1.7.1 and the issue is back again. Need help guys cant really work like this.

**Comment by masaeedu** [comment]
@DustinCampbell I've put up repro steps for a project.json codebase in #843.

**Comment by DustinCampbell** [comment]
OK. I'm going to close this issue. The latest bits are working for most folks and new issues have been opened for further work.

**Comment by HawkenKing** [comment]
same here, when I move the cursor, the red underline squiggles disappear.

I tried the patch csharp-1.5.0-future-preview1.vsix but same issue
